icons_format = "<span font_family='EnvyCodeR Nerd Font Propo' size='12pt'>{icon}</span>"

[theme.overrides]
idle_bg = "#0d2015"
idle_fg = "#c2c7c4"
info_bg = "#c2c7c4"
info_fg = "#0d2015"
good_bg = "#66B073"
good_fg = "#0d2015"
warning_bg = "#8FA86F"
warning_fg = "#0d2015"
critical_bg = "#689F68"
critical_fg = "#0d2015"
alternating_tint_bg = "#0d2015"
alternating_tint_fg = "#0d2015"
separator = "<span size='20pt'> </span>"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "none"

[icons.overrides]
cpu = "  "
cpu_boost_on = ""
cpu_boost_off = ""
memory_mem = "  "
memory_swap = " 󰋊 "
volume = ["󰕿", "󰖀", "󰕾"]
volume_muted = " 󰝟"
microphone = ["", "", ""]
microphone_muted = ""
headphones = ""
webcam = ""
net_wired = " 󰱓"
net_loopback = ""
net_modem = ""

[[block]]
block = "cpu"
interval = 2
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = "  $icon $utilization "

[[block.click]]
button = "right"
cmd = "sh ~/.config/sway/status/custom_status.sh --type=monitor system"

[[block]]
block = "memory"
format = "  $icon $mem_used_percents.eng(w:1) "
format_alt = "   $icon_swap$swap_used_percents.eng(w:2)  "

[[block]]
block = "custom"
interval = 0.5
command = "sh ~/.config/sway/status/custom_status.sh --type=bluetooth"

[[block.click]]
button = "left"
cmd = "sh ~/.config/sway/status/custom_status.sh --type=bluetooth toggle"

[[block.click]]
button = "right"
cmd = "bash ~/.config/rofi/scripts/bluetooth.sh"

[[block.click]]
button = "middle"
cmd = "bash ~/.config/sway/status/custom_status.sh --type=monitor bluetooth"

[[block]]
block = "custom"
interval = 2
command = "sh ~/.config/sway/status/custom_status.sh --type=wifi"

[[block.click]]
button = "right"
cmd = "bash ~/.config/rofi/show.sh wifi"

[[block]]
block = "net"
interval = 3
device = "eno1"
format = "  {<span size='5pt'> </span>$icon  <span rise='1000'>$ip</span>|󰛵  Cheking IP...}  "
inactive_format = "   󰅛  "

[[block]]
block = "sound"
driver = "auto"
format = "   $icon  {<span rise='-100'>$volume</span>|} "

[[block.click]]
button = "right"
cmd = "sh ~/.config/sway/status/custom_status.sh --type=monitor audio"

[[block.click]]
button = "left"
cmd = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

[[block]]
block = "custom"
cycle = ["sh ~/.config/sway/status/custom_status.sh --type=date", "sh ~/.config/i3/status/custom_status.sh --type=time"]

[[block.click]]
button = "left"
action = "cycle"

[[block.click]]
button = "right"
cmd = "sh ~/.files/resources/scripts/calendar.sh"

[[block]]
block = "custom"
interval = 2
command = "sh ~/.config/sway/status/custom_status.sh --type=monitor"

[[block.click]]
button = "left"
cmd = "bash ~/.config/sway/status/custom_status.sh --type=monitor screen"

[[block]]
block = "menu"
text = "  ⏻  "

[[block.items]]
display = "  ⏻  Performance  "
cmd = "powerprofilesctl set performance && notify-send 'Power Profile' 'Setting to performance...'"

[[block.items]]
display = "  ⏻  Balanced  "
cmd = "powerprofilesctl set balanced && notify-send 'Power Profile' 'Setting to balanced...'"

[[block.items]]
display = "  ⏻  Minimal  "
cmd = "powerprofilesctl set power-saver && notify-send 'Power Profile' 'Setting to power-saver...'"
