[colors.normal]
red = "#EF3A0C"
cyan = "#C5B497"
green = "#BD411C"
white = "#9b9790"
black = "#1f180d"
blue = "#A58F74"
magenta = "#B1A489"
yellow = "#E34F25"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
foreground = "#c7c5c2"
background = "#9b9790"

[colors.bright]
black = "#71685c"
red = "#c48676"
green = "#bc7864"
blue = "#cbad85"
cyan = "#dac7a9"
magenta = "#d2be97"
white = "#c7c5c2"
yellow = "#c78e7d"

[colors.primary]
background = "#1f180d"
foreground = "#c7c5c2"

[colors.cursor]
text = "#1f180d"
cursor = "#9b9790"

[colors.vi_mode_cursor]
text = "#1f180d"
cursor = "#c7c5c2"

[colors.search.matches]
foreground = "#1f180d"
background = "#c7c5c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[window.padding]
x = 12
y = 12

[font]
size = 12

[font.normal]
family = "EnvyCodeR Nerd Font Mono"

[font.bold]
family = "EnvyCodeR Nerd Font"
style = "Regular"
