[colors.normal]
red = "#93573C"
cyan = "#F0D7A4"
green = "#976648"
white = "#8f8f9a"
black = "#121316"
blue = "#D09F66"
magenta = "#CDB78C"
yellow = "#6F8D64"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
foreground = "#c3c4c4"
background = "#8f8f9a"

[colors.bright]
black = "#5b626f"
red = "#ba7c5f"
green = "#be8867"
blue = "#d1b695"
cyan = "#e6dcc6"
magenta = "#d9c9a7"
white = "#c3c4c4"
yellow = "#88c270"

[colors.primary]
background = "#121316"
foreground = "#c3c4c4"

[colors.cursor]
text = "#121316"
cursor = "#8f8f9a"

[colors.vi_mode_cursor]
text = "#121316"
cursor = "#c3c4c4"

[colors.search.matches]
foreground = "#121316"
background = "#c3c4c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[window.padding]
x = 12
y = 12

[font]
size = 12

[font.normal]
family = "EnvyCodeR Nerd Font Mono"

[font.bold]
family = "EnvyCodeR Nerd Font"
style = "Regular"
