[colors.normal]
red = "#A7633A"
cyan = "#FED052"
green = "#C56650"
white = "#98909b"
black = "#1c0d1f"
blue = "#BF9E51"
magenta = "#E28F62"
yellow = "#39847D"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
foreground = "#c6c2c7"
background = "#98909b"

[colors.bright]
black = "#6d5c71"
red = "#be8969"
green = "#ca9183"
blue = "#c9b381"
cyan = "#d7c9a3"
magenta = "#d4b09d"
white = "#c6c2c7"
yellow = "#55b6ad"

[colors.primary]
background = "#1c0d1f"
foreground = "#c6c2c7"

[colors.cursor]
text = "#1c0d1f"
cursor = "#98909b"

[colors.vi_mode_cursor]
text = "#1c0d1f"
cursor = "#c6c2c7"

[colors.search.matches]
foreground = "#1c0d1f"
background = "#c6c2c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[window.padding]
x = 12
y = 12

[font]
size = 12

[font.normal]
family = "EnvyCodeR Nerd Font Mono"

[font.bold]
family = "EnvyCodeR Nerd Font"
style = "Regular"
