[wallpaper]
cycle = "iterative"
type = "image"
path = "/home/akqir24/Pictures/Wallpapers"
mode = "fill"
animated = true

[theming]
gtk = true
icons = true
mode = "dark"
accent = "color2"

[theming.programs]
i3status_rust = "/home/akqir24/.files/.config/sway/status/config.toml"
alacritty = "/home/akqir24/.config/alacritty.toml"
rofi = "/home/akqir24/.config/rofi/config.rasi"
dunst = "/home/akqir24/.config/dunst/dunstrc"

[pywal16]
light = true
reload = true
backend = "wal"
colorscheme = "lighten"
